name: app_for_santa
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #intl
  intl: ^0.18.1

  #env
  envied: ^0.3.0+3

  #dependency injection
  get_it: ^7.6.0
  injectable: ^2.3.0

  #state management
  flutter_bloc: ^8.1.3

  #router
  auto_route: ^7.8.0

  #google fonts
  google_fonts: ^6.1.0

  #adaptive sizes
  adaptive_sizer:
    git:
      url: https://github.com/kishor98100/adaptive_sizer

  #image and svg renderer
  flutter_svg: ^2.0.7

  #data models
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  #native splash
  flutter_native_splash: ^2.3.3

  #logger
  logger: ^2.0.1

  #functional programming
  fpdart: ^1.1.0

  #url launcher
  url_launcher: ^6.1.14
  dots_indicator: ^3.0.0

  #flutter slidable
  flutter_slidable: ^3.0.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  #generators
  build_runner: ^2.4.6
  ferry_generator:

  #dependency injection
  injectable_generator: ^2.4.0

  #route generator
  auto_route_generator: ^7.3.1

  #envied generator
  envied_generator: ^0.3.0+3

  #assets generator
  flutter_gen_runner: ^5.3.2

  #freezed
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - google_fonts/plus jakarta sans/

#flutter intl
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/localization/arb
  output_dir: lib/localization/generated

#native splash
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/santa_icon.png
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
  android_12:
    image: assets/images/santa_icon.png
    icon_background_color: "#FFFFFF"

#flutter asset generator
flutter_gen:
  output: lib/gen/
